### PR TITLE
Migrate from dep to Go modules

### PR DESCRIPTION
**Pull request by sslavic**
Towards giantswarm/giantswarm#6302

As part of updating k8s dependencies I'm taking the opportunity to try to switch to Go modules as well in the same go. Our tooling like architect and e2e-harness have already been updated to Go 1.13 so Go modules support should be best ever.

Related:
giantswarm/giantswarm#5680

### CODE REVIEW

**Comment by kopiczko** [comment]
For our internal libraries during the transition period I think it would be wise to keep both dep and modules files. WDYT?

**Comment by sslavic** [comment]
> For our internal libraries during the transition period I think it would be wise to keep both dep and modules files. WDYT?

Not sure what would be the benefit; it can cause problems like dependency info getting out of sync.

Anyway, since there are still issues with Go modules and k8s libraries as dependencies, lets put migration of these other leaf projects to Go modules on hold as well. IMO it only makes sense to migrate if we can use Go modules consistently across all or at least majority of the projects.

**Comment by corest** [comment]
What is the status of this?

**Comment by rossf7** [comment]
I'd like us to keep this PR open because we'll be working on the Helm 3 migration soon. We'll need PRs for all libraries used by helmclient.

There is also now @giantswarm/wg-go-modules. I think it would be good to have a new issue tracking these PRs.

**Comment by omegas27** [comment]
@rossf7 as you have more knowledge than on me the current go modules PR, would you mind creating the issue for the WG so we can ping it in the slack channel?

**Comment by rossf7** [comment]
@omegas27 Yes sure I'll create an issue.

**Comment by oponder** [comment]
I’m trying to get a real list of requested reviews when I look at the PRs tab. Would it be alright to remove the reviewers until this PR  is again ready for further input / review?

**Comment by xh3b4sd** [comment]
Since this is stale I redo it from scratch.

**Pull request closed without merging**
